version: '2'
services:
  kodi-mysql-server:
    build: KodiMySQLServer/
    ports:
     - "3306:3306"
    # Store kodi mysql library in a volume so it can be easily backed up and is not incorporated in container updates.
    volumes:
     - kodi-mysql-data:/var/lib/mysql
volumes:
  kodi-mysql-data:
    driver: local
